hive> CREATE TABLE characterscount (name STRING, line STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' TBLPROPERTIES ("skip.header.line.count"="2");
hive> LOAD DATA LOCAL INPATH 'root/ProjectActivities/' INTO TABLE characterscount;
hive> SELECT name, count(name) AS no_of_lines from characterscount GROUP BY name ORDER BY no_of_lines;

hive> INSERT OVERWRITE DIRECTORY '/user/lakshmi/output/projectActivityResults'
    > ROW FORMAT DELIMITED FIELDS TERMINATED BY ','
  > SELECT name, count(name) AS no_of_lines from characterscount GROUP BY name ORDER BY no_of_lines;

hive> dfs -cat /user/pranathi/output/projectActivityResults/000000_0;  